config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: :show
  root 'welcome#index'
  resources :tasks
 

  resources :events do 
    resources :tasks, only: [:show, :edit]
  end

  get '/signup' =>'users#new'
  post '/signup' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post  '/logout' => 'sessions#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  #change testing
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :user
    validates :title, presence: true
    validates :date, presence: true


    def today
        Date.todays
    end

    def seven_days_later
        Date.today + 7 
    end

    def self.collect_weekly_events
        where("date_object >= ? AND date_object <=?", Date.today, Date.today + 7 ).order(date_object: :asc)
       #binding.pry
    end

    def self.found_event(date, current_user)
        where("date = ? AND user_id = ?", date, current_user.id)
    end

    
end

app/models/user.rb
class User < ApplicationRecord
    has_many :events 
    has_many :tasks, through: :events
    has_secure_password 
    validates :username, presence: true
    validates :username, uniqueness: true
    validates :password, presence: true

    # def self.from_omniauth(auth)
    #     where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |user|
    #       user.provider = auth.provider
    #       user.uid = auth.uid
    #       user.name = auth.info.name
    #       user.oauth_token = auth.credentials.token
    #       user.oauth_expires_at = Time.at(auth.credentials.expires_at)
    #       user.save!
    #     end
    #   end

      def self.find_or_create_by_omniauth(auth_hash)
        self.where(:username => auth_hash["info"]["first_name"]).first_or_create do |user|
            user.provider = auth_hash.provider
            user.password = SecureRandom.hex
            user.uid = auth_hash.uid
            user.name = auth_hash.info.name
            user.oauth_token = auth_hash.credentials.token
            user.oauth_expires_at = Time.at(auth_hash.credentials.expires_at)
            user.save!
        end
      end


  

      
    


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?, :require_login

    #:days_in_month, :starting_div_class, :number_of_blank_days, :add_empty_divs, :month_name

    # def starting_div_class
    #     date = Date.today - Date.today.day
    # end

    # def month_name
    #     Date::MONTHNAMES[Date.today.month]
    # end


    # def number_of_blank_days
    #     date = Date.today - Date.today.day
    #     date.cwday + 1 
    # end

    # def add_empty_divs
    #     empty_divs = []
    #     number_of_blank_days.times do 
    #         empty_divs << "<div></div>"
    #     end
    #     #binding.pry
    #     empty_divs.join
    # end

    
    # def days_in_month
    #     m = Date.today.month 
    #     y = Date.today.year
    #     days = Time.days_in_month(m, y)
    # end

    def require_login
        return redirect_to(controller: 'sessions', action: 'new') unless logged_in?
    end
  
    def current_user
        @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
    end
  
    def logged_in?
        !current_user.nil?
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :require_login

    def index 
        @events = Event.collect_weekly_events
        @user = current_user
        #binding.pry
    end

    def new
        @event = Event.new

    end

    def show
        @event = Event.find_by(id: params[:id])
    end
     
    def edit 
        @event = Event.find_by(id: params[:id])
    end

    def update
        @event = Event.find_by(id: params[:id])
        # @event.date = Date.new(params[:event]["date(1i)"].to_i, params[:event]["date(2i)"].to_i, params[:event]["date(3i)"].to_i)
         if @event.update(event_params)
            #update date object? event.date_object = @event.date.to_date
            redirect_to event_path(@event)
        else
            redirect_to edit_event_path(@event)
        end       
    end


    def create
        @event = Event.new(event_params)
        @event.user = current_user
        @event.date = Date.new(params[:event]["date(1i)"].to_i, params[:event]["date(2i)"].to_i, params[:event]["date(3i)"].to_i)
        @event.date_object = @event.date.to_date
        
        if @event.save
            redirect_to event_path(@event)
          
        else
            @event.date = Date.today
            @user = current_user
            render "users/show"
        end

    end

    def destroy
        @event = Event.find_by(id: params[:id])
        @event.destroy
        redirect_to user_path(current_user.id)
    end


    

    private
    
    def event_params
        params.require(:event).permit(:title, :description, :start_time, :end_time, "date(1i)", "date(2i)", "date(3i)", :date_object)
    end

    def require_login
        return redirect_to(controller: 'sessions', action: 'new') unless logged_in?
    end

end

app/controllers/months_controller.rb
class MonthsController < ApplicationController 

    def new
        #Don't believe we need a new action. we are not rendering a new form. we need to change the month
        @old_month =
    end

    def create  
        #instantiate the new month, based on the previous month (submitted as a form)
        #catch the old month and add 30 calendar days
        #instantiate the new starting div day, and month name
        redirect_to show_path(@month)

    end

    def show
        #instantiate new task and new event for form on new month
        #find the new month from the url
    end



end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    
    def new
        @user = User.new
    end

    def create
           login_with_credentials
        end

    end

    def destroy
        session.delete :user_id
        redirect_to root_path
    end
    
    def login_with_credentials
        user = User.find_by(username: params[:user][:username])
        
        if user && user.authenticate(params[:user][:password])
            session[:user_id] = user.id
            @user = user
            redirect_to user_path(@user)
        else
            @user = User.last
            redirect_to login_path
        end
       
    end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :require_login, only: [:new, :create]
    def new
      @user = User.new
    end
  
    def create
      @user = User.new(user_params)
        if @user.save
          session[:user_id] = @user.id
          redirect_to user_path(@user)
        else
          render :new
        end
    end
  
    def show
      if logged_in?
        @user = User.find_by(id: params[:id])
        @event = Event.new
        render :show
      else
        redirect_to root_path
      end
      
    end

    private

    def user_params
      params.require(:user).permit(:username, :password)
    end

    def require_login
      return redirect_to(controller: 'sessions', action: 'new') unless logged_in?
    end

end

  

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

    def index
        #render landing page with signup and login link! 
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
    def starting_div_class
        date = Date.today - Date.today.day
    end

    def month_name
        Date::MONTHNAMES[Date.today.month]
    end


    def number_of_blank_days
        date = Date.today - Date.today.day
        date.cwday + 1 
    end

    def add_empty_divs
        empty_divs = []
        number_of_blank_days.times do 
            empty_divs << "<div></div>"
        end
        #binding.pry
        empty_divs.join
    end

    
    def days_in_month
        m = Date.today.month 
        y = Date.today.year
        days = Time.days_in_month(m, y)
    end
end

app/views/events/edit.html.erb
<div class="edit_event_form">
<%= form_for(@event) do |f| %>
    <%= f.label :date_object %>
    <%= f.date_select :date_object%><br>
    <%= f.label :title %>
    <%= f.text_field :title %><br>
    <%= f.label :description %>
    <%= f.text_field :description %><br>
    <%= f.label :start_time %>
    <%= f.text_field :start_time %><br>
    <%= f.label :end_time %>
    <%= f.text_field :end_time %><br>

    <%=f.submit "Create Event"%>
<% end %>
</div>

app/views/events/index.html.erb
<%= link_to "Home", user_path(@user) %>


<h1> The Week Ahead </h1>
<div class="week_ahead">
<ul>
<% @events.uniq.each do |e| %>
    <li><%= e.date%> - <%= link_to e.title, event_path(e) %> </li> 
    <% end %>
</ul>
</div>

app/views/events/show.html.erb
<%= link_to "back to report", events_path %>
<%= link_to "home", user_path(@event.user_id) %>
<div class="show_content">
<h1><%= @event.title.titleize %></h1> 
on <%= @event.date %> from <%=@event.start_time%> until <%=@event.end_time %>
<p><%= @event.description%></p>

<%= link_to "Edit", edit_event_path(@event)%> <%= link_to "Delete", event_path(@event), method: 'delete' %><br>
<h3> TO DO </h3>
<hr>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyCalApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div>
  <%= form_tag ({controller: 'sessions', action: 'destroy', method: 'POST'}) do %>
    <input type="submit" value="Log Out">
    <% end %> 

  <div>
    <%= yield %>
  
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up Here! </h1>

<%= form_for @user, url: signup_path, method: :post do |f| %>
    <%= f.label :username %>
    <%= f.text_field :username %>
  
    <%= f.label :password %>
    <%= f.password_field :password %>
  
    <%= f.submit "Sign up" %>
  <% end %>

  <% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this account from being created:</h2>
 
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/show.html.erb
  <%= link_to "See your Weekly Report", events_path %>
<h1 class="month_title"> <%= month_name%> </h1>
<% stylesheet_link_tag "/calendar" %>
<ul class="weekdays">
  <li>Sun</li>
  <li>Mon</li>
  <li>Tue</li>
  <li>Wed</li>
  <li>Thu</li>
  <li>Fri</li>
  <li>Sat</li>
</ul>

<div class="grid-container">
<% add_empty_divs %>

<% i = 1 %>
<% while i <= days_in_month %> 
  <div class="<%= starting_div_class + i %>"><%= i %>
 
    <% if Event.found_event(starting_div_class + i, current_user) %>
      <ul><% Event.found_event(starting_div_class + i, current_user).each do |event| %>
        <li><%= event.title %></li>
      <% end %>
      </ul>
    <% end %> 
  
  
  </div>
  <% i += 1 %>
  <% end %> 
</div>


<hr>
<hr>
<h2 class="home_page">Add an Event</h2>
<div class="new_event_form">
  <%= form_for(@event) do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %><br>
      <%= f.label :description %>
      <%= f.text_field :description %><br>
      <%= f.label :date %>
      <%= f.date_select :date, selected: Date.today%><br>
      <%= f.label :start_time %>
      <%= f.text_field :start_time %><br>
      <%= f.label :end_time %>
      <%= f.text_field :end_time %><br>

      <%=f.submit "Create Event"%>
  <% end %>
</div> 

<h2 class="home_page">Add a Task</h2>

<% if @event.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@event.errors.count, "error") %> prohibited this EVENT from being saved:</h2>
 
    <ul>
    <% @event.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/welcome/index.html.erb
<%= link_to "Sign Up", signup_path %><br>
<%= link_to "Login", login_path %><br>